/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment.forms;

import payment.forms.components.SharedPanel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import payment.information.MasterCardPaymentInformation;
import payment.information.PaymentInformation;

/**
 *
 * @author mdjukanovic
 */
public class FrmMasterCard extends BasePaymentForm {

    /**
     * Creates new form FrmMasterCard
     */
    public FrmMasterCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMasterCard = new payment.forms.components.SharedPanel();
        lblOwner = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        txtOwner = new javax.swing.JTextField();
        txtPin = new javax.swing.JTextField();
        txtCardNumber1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOwner.setText("Owner:");

        lblCardNumber.setText("Card number:");

        lblPin.setText("Pin:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOwner)
                            .addComponent(lblCardNumber))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOwner)
                            .addComponent(txtPin)
                            .addComponent(txtCardNumber1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMasterCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwner)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panelMasterCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblPin;
    private payment.forms.components.SharedPanel panelMasterCard;
    private javax.swing.JTextField txtCardNumber1;
    private javax.swing.JTextField txtOwner;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables
   
    @Override
    public void fillData(double price) {
        panelMasterCard.getTxtPrice().setText(String.valueOf(price));
    }

    @Override
    public  PaymentInformation paymentInformation() {
        String owner = txtOwner.getText().trim();
        String cardNumber = txtCardNumber1.getText().trim();
        String pin = txtPin.getText().trim();
        double price = Double.parseDouble(panelMasterCard.getTxtPrice().getText());
        
        PaymentInformation paymentInformation = new MasterCardPaymentInformation(owner, cardNumber, pin, price);

        return paymentInformation;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getLblCardNumber() {
        return lblCardNumber;
    }

    public JLabel getLblOwner() {
        return lblOwner;
    }

    public JLabel getLblPin() {
        return lblPin;
    }

    public SharedPanel getPanelMasterCard() {
        return panelMasterCard;
    }

    public JTextField getTxtCardNumber1() {
        return txtCardNumber1;
    }

    public JTextField getTxtOwner() {
        return txtOwner;
    }

    public JTextField getTxtPin() {
        return txtPin;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setLblCardNumber(JLabel lblCardNumber) {
        this.lblCardNumber = lblCardNumber;
    }

    public void setLblOwner(JLabel lblOwner) {
        this.lblOwner = lblOwner;
    }

    public void setLblPin(JLabel lblPin) {
        this.lblPin = lblPin;
    }

    public void setPanelMasterCard(SharedPanel panelMasterCard) {
        this.panelMasterCard = panelMasterCard;
    }

    public void setTxtCardNumber1(JTextField txtCardNumber1) {
        this.txtCardNumber1 = txtCardNumber1;
    }

    public void setTxtOwner(JTextField txtOwner) {
        this.txtOwner = txtOwner;
    }

    public void setTxtPin(JTextField txtPin) {
        this.txtPin = txtPin;
    }

    @Override
    public JButton getTransactionButton() {
        return panelMasterCard.getBtnTransaction();
    }
   
    @Override
    public JButton getBackButton() {
        return panelMasterCard.getBtnBack();
    }
}
