/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment.forms;

import payment.forms.components.SharedPanel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import payment.information.PayPalPaymentInformation;
import payment.information.PaymentInformation;
import payment.information.VisaPaymentInformation;

/**
 *
 * @author mdjukanovic
 */
public class FrmVisaCard extends BasePaymentForm {

    /**
     * Creates new form FrmVisaCard
     */
    public FrmVisaCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPin = new javax.swing.JLabel();
        txtPin = new javax.swing.JTextField();
        lblCardNumber = new javax.swing.JLabel();
        txtCardNumber1 = new javax.swing.JTextField();
        txtOwner = new javax.swing.JTextField();
        lblOwner = new javax.swing.JLabel();
        panelVisaCard = new payment.forms.components.SharedPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        lblPin.setText("Pin:");

        lblCardNumber.setText("Card number:");

        lblOwner.setText("Owner:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPin)
                    .addComponent(lblOwner)
                    .addComponent(lblCardNumber))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCardNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVisaCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwner)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVisaCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblPin;
    private payment.forms.components.SharedPanel panelVisaCard;
    private javax.swing.JTextField txtCardNumber1;
    private javax.swing.JTextField txtOwner;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fillData(double price) {
           panelVisaCard.getTxtPrice().setText(String.valueOf(price));
     }

    @Override
    public PaymentInformation paymentInformation() {
        String owner = txtOwner.getText().trim();
        String cardNumber = txtCardNumber1.getText().trim();
        String pin = txtPin.getText().trim();
        double price = Double.parseDouble(panelVisaCard.getTxtPrice().getText());
        
        PaymentInformation paymentInformation = new VisaPaymentInformation(owner, cardNumber, pin, price);
        
        return paymentInformation;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getLblCardNumber() {
        return lblCardNumber;
    }

    public JLabel getLblOwner() {
        return lblOwner;
    }

    public JLabel getLblPin() {
        return lblPin;
    }

    public SharedPanel getPanelVisaCard() {
        return panelVisaCard;
    }

    public JTextField getTxtCardNumber1() {
        return txtCardNumber1;
    }

    public JTextField getTxtOwner() {
        return txtOwner;
    }

    public JTextField getTxtPin() {
        return txtPin;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setLblCardNumber(JLabel lblCardNumber) {
        this.lblCardNumber = lblCardNumber;
    }

    public void setLblOwner(JLabel lblOwner) {
        this.lblOwner = lblOwner;
    }

    public void setLblPin(JLabel lblPin) {
        this.lblPin = lblPin;
    }

    public void setPanelVisaCard(SharedPanel panelVisaCard) {
        this.panelVisaCard = panelVisaCard;
    }

    public void setTxtCardNumber1(JTextField txtCardNumber1) {
        this.txtCardNumber1 = txtCardNumber1;
    }

    public void setTxtOwner(JTextField txtOwner) {
        this.txtOwner = txtOwner;
    }

    public void setTxtPin(JTextField txtPin) {
        this.txtPin = txtPin;
    }
    
      @Override
    public JButton getTransactionButton() {
        return panelVisaCard.getBtnTransaction();
    }

    @Override
    public JButton getBackButton() {
        return panelVisaCard.getBtnBack();
    }
    
}
